### ISSUE TITLE
Docker build failing on master

### ISSUE THREAD

**Issue by kepi** [justwatchcom/gopass#669]
Hi, I wanted to test new history command but unfortunately docker build is failing:

```
~/dev/os/gopass master  
❯ make docker-test
docker build -t gopass:fca7151a .
Sending build context to Docker daemon  22.62MB
Step 1/9 : FROM golang:1.9-alpine AS builder
 ---> a8f345e387a3
Step 2/9 : RUN apk add -U make git gnupg
 ---> Using cache
 ---> d1c27e05a2de
Step 3/9 : ADD . /go/src/github.com/justwatchcom/gopass
 ---> 9ee1df92060f
Removing intermediate container 3646a5706d86
Step 4/9 : WORKDIR /go/src/github.com/justwatchcom/gopass
 ---> 4b445abc25fb
Removing intermediate container 6e228320021e
Step 5/9 : RUN make install
 ---> Running in 1bb665bea5d6
>> BUILD, version = 1.6.11/fca7151a, output = gopass# github.com/justwatchcom/gopass/store/secret
store/secret/kv.go:64:10: undefined: strings.Builder
store/secret/secret.go:64:10: undefined: strings.Builder
make: *** [Makefile:69: build] Error 2
The command '/bin/sh -c make install' returned a non-zero code: 2
make: *** [Makefile:208: docker-test] Error 2
```

**Comment by kepi** [comment]
Looks like build stopped working in c63520ca4df47d058382d811e20cce6065721c02 previous commit is building fine.

**Comment by dominikschulz** [comment]
Of course, `strings.Builder` is new in Go 1.10. Sorry, forgot to update the Dockerfile.
